name: Deploy to Google Cloud Functions (2nd Gen)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Authenticate using Workload Identity Federation
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}

      - name: Deploy to Cloud Functions
        uses: google-github-actions/deploy-cloud-functions@v2
        with:
          name: divide-numbers
          region: us-central1
          runtime: python310
          entry_point: divide_numbers
          source_dir: .
          project_id: ${{ secrets.GCP_PROJECT_ID }}
